"""nullable_supplier_id

Revision ID: ce9231bf3b56
Revises: 3b572b2b1b1a
Create Date: 2026-04-24 21:36:06.634921

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ce9231bf3b56'
down_revision: Union[str, None] = '3b572b2b1b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'supplier_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'supplier_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
